manifest:
  remotes:
  #  - name: urob
    - name: petejohanson      
  #     url-base: https://github.com/urob
     url-base: https://github.com/petejohanson
  projects:
    - name: zmk
   #    remote: urob  
    remote: petejohanson
  #    revision: main   
     revision: features/soft-off-take-2
      import: app/west.yml
  self:
    path: config
